
-- CREAR BASE DE DATOS CON EL NOMBRE DE "db_ferreteria"

CREATE TABLE PRODUCTOS(
    CODIGO_PRO VARCHAR(10)NOT NULL PRIMARY KEY,
    DESCRIBE_PRO VARCHAR(60)NOT NULL UNIQUE,
    MARCA_PRO VARCHAR(10)NOT NULL
);